### ISSUE TITLE
大神，这是有bug么？

### ISSUE THREAD

**Issue by ChineseBoyLY** [JessYanCoding/RetrofitUrlManager#10]
![image](https://user-images.githubusercontent.com/35990186/40224870-1bd76c56-5aba-11e8-8f70-c9306cf1a038.png)

RetrofitUrlManager.getInstance().putDomain("douban", "https://api.douban.com")

@Headers({"Domain-Name: douban"}) // 加上 Domain-Name header
    @GET("/v2/book/{id}")
    Call<ResponseBody> getBook(@Path("id") int id);

**Comment by JessYanCoding** [comment]
网络的问题, 和框架没有关系
