### ISSUE TITLE
retrofit  返回数据拦截器,后台接口,解密,  第三方接口,不解密,怎么处理

### ISSUE THREAD

**Issue by EvanEvil** [JessYanCoding/RetrofitUrlManager#11]
![qq 20180531105451](https://user-images.githubusercontent.com/23189683/40758743-67ffcb44-64c1-11e8-938c-f6e4f61db714.png)

**Comment by JessYanCoding** [comment]
这里只接受与 **RetrofitUrlManager**  有关的问题，兄弟

**Comment by EvanEvil** [comment]
解决了
