### ISSUE TITLE
麻烦能加上对encodedPath的支持吗？因为BaseUrl不只是有标准格式

### ISSUE THREAD

**Issue by weiaiSanli** [JessYanCoding/RetrofitUrlManager#12]
http://www.baidu.com:8080 目前只能是这种格式的BaseUrl验证，在DefaultUrlParser类中添加
`return url.newBuilder()
                .scheme(domainUrl.scheme())
                .host(domainUrl.host())
                .port(domainUrl.port())
                .encodedPath(domainUrl.encodedPath() + url.encodedPath()) // url的第三个 / 以后的 path路径
                .build();` 
http://www.baidu.com:8080 /youpath/随意   的支持！Thanks,亲测可用~

**Comment by JessYanCoding** [comment]
兄弟你想的太简单了, 你的方式只是将他们的 encodedPath 相加, 以你的算法, 如果旧 URL 地址为 https://www.github.com/wiki/part, 其中 BaseUrl 为 https://www.github.com, 你调用 {@link RetrofitUrlManager#putDomain(String, String)}方法传入的 URL 地址是 https://www.google.com/api,
最后得出的新地址为 https://www.google.com/api/wiki/part，ok 很完美, 得到了使用者想要的地址

但如果使用者的  BaseUrl 是 https://www.github.com/wiki, 这时你的算法生成的新地址还是 https://www.google.com/api/wiki/part, 但是明显使用者是想让 https://www.google.com/api 去替换https://www.github.com/wiki, 得到 https://www.google.com/api/part 这个地址, 这时你的算法出问题, 因为你不知道使用者的 BaseUrl 到底是什么, 使用者甚至还可能把 https://www.github.com/wiki/part 都设为BaseUrl, 所以你的算法考虑的还不够全面, 既然要做就要做到尽可能的完美, 不过还是感谢你的建议

**Comment by JessYanCoding** [comment]
之前没做个需求就是因为这个地方，考虑的东西有点多，弄的有点复杂，不过最近也有点思路了，正在研发这个地方

**Comment by JessYanCoding** [comment]
![1528791124577](https://user-images.githubusercontent.com/15711968/41279224-7a64f286-6e5e-11e8-9ed0-fc083aa3174b.jpg) 正在做一个新的 UrlParser 运用一个更为复杂的新算法

**Comment by weiaiSanli** [comment]
嗯,今天我也在看这个UrlParser的分解方式,只是提供一个思路解决我遇到的问题,期待你能完善解决这些,给与使用者更多的扩展性!

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/RetrofitUrlManager/blob/master/manager/src/main/java/me/jessyan/retrofiturlmanager/parser/DefaultUrlParser.java    
直接重写了全部 UrlParser, 可随意替换多级 URL, 你上面的需求, 让多级 URL 替换 域名, 现在什么都不用改就可以实现, 如果想 多级 URl 替换 多级 BaseUrl，通过 RetrofitUrlManager#startAdvancedModel(String baseUrl) 开启高级模式即可实现

再优化下框架, 更新下 Demo, 就上传远程库

**Comment by JessYanCoding** [comment]
implementation 'me.jessyan:retrofit-url-manager:1.3.0'
