### ISSUE TITLE
涉及到不同的baseUrl需要使用不同的okhttp配置能够解决么

### ISSUE THREAD

**Issue by ding33211** [JessYanCoding/RetrofitUrlManager#13]

**Comment by JessYanCoding** [comment]
不知道你在说什么

**Comment by ding33211** [comment]
针对知乎的我的超时时间是5s，针对github的我需要加拦截但是超时时间是10s，针对微博的我需要加header等等。根据不同的baseurl配置不同的okhttpClient。。。很难理解么。。

**Comment by JessYanCoding** [comment]
你的意思在项目中不同域名的网络请求不仅仅是 BaseUrl 不同，他的超时时间等 Okhttp 配置也不同，但想通过使用同一个 Okhttp 实例来完成，你标题这句话描述的也不清楚，我怎么知道你要表达什么，后面的这句话刚开始就补在标题下面不就完了

**Comment by JessYanCoding** [comment]
这个库只管 baseUrl 的切换，其他 Okhttp 的配置不是它的指责，不过超时时间倒是可以提示下你，可以通过 Okhttp 拦截器解决

**Comment by ding33211** [comment]
所以可以解决么？你是心情不好么？之前认识？有仇？项目一般，为脾气点赞。

**Comment by JessYanCoding** [comment]
不用删，我 App 的推送已经看到了你的留言，下面是你的留言


```
所以可以解决么？你是心情不好么？之前认识？有仇？项目一般，为脾气点赞。
```

1. 解决方案后面已经详细回答你了，也给了提示

2.关于态度，是你自己对问题不描述清晰，对问题描述清晰这是提问的常识，你觉得容易理解的东西，别人并不一定理解，我只是说了句我不知道你在说什么，事实上确实我也不知道你的意思

后面你的回复就已经带有情绪了不耐烦了，还指望我对你毕恭毕敬？而且在你带情绪的情况下，我还是给了你答案和提示

你用开源也没收你费，不尊重开源作者的情况下，还想让我对你态度友好？稍有不满意就攻击开源项目的代码？我觉得你根本不配用开源

你觉得项目不行，你能在做完公司业务外的空余时间为开源社区贡献点优质代码吗？

**Comment by JessYanCoding** [comment]
Open 让更多人看到，如果所有人用开源的人都像你这样，那将没有人愿意开源

**Comment by xiaohaoWit** [comment]
点赞

**Comment by ding33211** [comment]
最近一段时间比较忙，就像你说的公司业务做不过来。
首先，我对一时冲动写下来为脾气点赞的追评做出抱歉，如果这句话有让你感到不适，实在是对不住。

在这里我希望可以针对你的情况说一下我个人的看法。
1. 你虽然作为当事人。你可能知道，或者你也可能不知道整件事情的经过。
   在此，我希望能够允许我将过程还原给可能看到或者看不到的广大开源者与使用开源者和所谓的贪婪的使用开源者看一下。
   首先即使工作再忙，我会抽出时间关注一下当前的开源动态，结果看到了阁下开源的这个Retrofit工具。每天开源的有千千万，但是这个我比较感兴趣，因为很有可能我们的多个项目可以使用到，可以推广给手下的同学们。
   在读了sample之后发现可能并不能解决多baseurl的多okhttp配置问题。于是便点开issue，总共8个提问，那就顺势找一下，如果有类似提问，那就可以不劳烦阁下了。结果逐个看下去的时候发现了类似这些交流过程。

![image](https://user-images.githubusercontent.com/8023129/42792842-cda7a518-89a9-11e8-8d75-1cc4862647bd.png)


   心里暗地里可能已经觉得不是非常好沟通的一位开源者。但是觉得工具又确实有价值，从而真的希望可以得到阁下的帮助。于是还是做出了提问，readme中指出项目与okhttp强绑，所以觉得阁下应该对整个okhttp的使用方式比较了解，所以觉得不需要做过多解释，贴过多代码，阁下应该可以理解。提问如下。

   涉及到不同的baseUrl需要使用不同的okhttp配置能够解决么

   阁下的回复如下。

   不知道你在说什么

   那天特别忙，在开会途中收到了阁下的回复，看到这些个字眼，心想果然中招了。当时也怪自己，怎落的一样的田地，于是将问题for ex的描述了一遍，也对自己和阁下都无奈的说了句很难理解么…，回复如下。

   紧跟着阁下回复如下。

   你的意思是在项目中不同域名的网络请求不仅仅是 BaseUrl 不同，他的超时时间等 Okhttp 配置也不同，但想通过使用同一个 Okhttp 实例来实现吗，你标题这句话描述的也不清楚，我怎么知道你想要表达什么... 后面的这句话提问时就主动补在标题下面不就清晰明了了


   其实看到这边，就可能有点懵逼了。阁下竟然在提问上跟我一个所谓的贪婪使用开源者纠缠那么久，并且没有给出解答，略感失望。并且字里行间的意味各位可以自行感受。

   不知道你在说什么，我怎么知道你想要表达什么。也许还是开源逛的少吧，可能见到更多的是可以说清楚一些么？哦，我理解你的意思了。

   不加思索的做了如下回复：

   所以可以解决么？你是心情不好？之前认识？有仇？项目一般，为脾气点赞。

   讲真这是气话，得不到实用的回答，却不断地做其他纠缠让我很是失望，提交回复的瞬间，拉到了阁下的回复如下：

   这个库的功能只是 baseUrl 的切换，其他 Okhttp 的配置切换不是它的职责，不过超时时间倒是可以提示下你，你可以通过 Okhttp 的拦截器来对不同的 Url 进行修改，至于你想实现其他的 Okhttp 的不同配置，有些是可以使用同一个 Okhttp 实例实现的，但是有些配置是 Okhttp 创建后就不能修改的，这个要你自己去看 API

   其他不说最起码收到了有用的回复，确实是无法实现的，需要自行实现，果断删除刚才的气话，command + w了

   结果当我再次回来观察切换baseurl的实现方式时出现了这一幕，事情的经过就是这样。

   在此只还原经过，不做评论。

2. 其实我一直以为，也许在阁下看来是错误的以为，开源者和使用者大家是公平的对等关系，本没有优劣之分，本是互相尊敬的关系，而在我看来，平淡的交流就是最公平的体现，我们不需要过多的去修饰我们交流的话术，带上过多的尊敬辞藻，就像朋友一样。
   我不会去跟朋友说，不好意思，我有个问题想要问你，如果有什么冒犯的话可以原谅我一下么，就像这样：

   
![image](https://user-images.githubusercontent.com/8023129/42792854-de8b0d16-89a9-11e8-9ede-d1d01d13ce06.png)


   你可以去揣测一下这种提问的心态，潜移默化的反映出一种阴暗的心理状态，或者是受过伤，或者是将开源者摆在高台，不可撼动。感觉是大臣提了逆耳的忠言，生怕火速被赐死。看到了这些言论，我更加的害怕，平日里身体力行的如此提问，在自己的地盘一旦遇到直白的提问是多么可怕的一种体验。与阁下的身份相违背：

   
![image](https://user-images.githubusercontent.com/8023129/42792866-efcb036a-89a9-11e8-88fe-9f119dd80879.png)


   对此也不做过多评论。

3. 没有为开源社区做过贡献的并非是不愿意奉献的人，为开源社区做出贡献的也并非是优秀的人。作为技术人，大家都不可能在这个圈子混一辈子，我们终将脱离技术，面对之后更宽广的人生舞台，届时不是可以通过几行代码就可以解决所有的问题，这也是为什么情商被排在了智商以前。

   一个好的开源作品的极致难道不是开源者与使用者“打”成一片？而是打成一片么？

   希望阁下可以摆正心态，多看看五彩缤纷的世界，多与更多的人接触和交流，体会沟通的艺术，摆脱那颗时刻爆裂的玻璃心与不可一世的高傲。


最后无论是否可以代表贪婪的摄取开源作品的技术人

再次对阁下的不当言论做出道歉，对开源者表示敬意，对仅存的或者是多数的善于交谈和措辞的开源者献上最真诚的致意。

对非技术探讨不做md，此问终结。

**Comment by JessYanCoding** [comment]
您好，事情已经发生这么多天了，我现在也可以非常理性的回答这个问题

当时写的上面的回复，我确实是非常生气的，理由无非是我可能态度不是对您特别友好，但是我却是认真的回答您的问题的，没有避而不答，也没三两语应付，虽然没有能给您立即可用的解决方案，但我还是热心的给了这么多字的提示，这时你却被别人莫名其妙的骂了一顿，如果是您，会是什么想法？关于您说的你回复那句话时，我还没写下这句话

"这个库的功能只是 baseUrl 的切换，其他 Okhttp 的配置切换不是它的职责，不过超时时间倒是可以提示下你，你可以通过 Okhttp 的拦截器来对不同的 Url 进行修改，至于你想实现其他的 Okhttp 的不同配置，有些是可以使用同一个 Okhttp 实例实现的，但是有些配置是 Okhttp 创建后就不能修改的，这个要你自己去看 API"

这个是我回复您之前就关注了的细节，因为我也想到了您可能是没看到这句话只看到了上一句才气到了，说出了上面的话，但这两句话发送时间也就间隔一两分钟，而且我看了您的那句回复的时间，是在这两句话回复后一小时之后回复的，所以我排除了这个可能，所以也更加生气，才说了上面的话

至于您贴的让您觉得我不好说话的那个 Issues，我也没必要回避，我确实是很讨厌不详细描述问题的这种行为，这也是对自己的问题，以及作者的不够尊重，所以关于态度我确实抱歉，但是提这种问题的人也是有问题的，如果我不指出这个问题，那他会继续的以这种格式去给其他框架提 Issues，Issues 的沟通并不如 IM 效率高，每一轮回复都可能间隔几小时或者几天，这也是对双方时间的浪费，所以我也在我的另一个框架中明确的指出了 [提 Issues 的规范](https://github.com/JessYanCoding/MVPArms/issues/150)，也许您可能不理解我为何要对这种小事这么上心？但如果您收到几十上百的这种类型的 Issues，可能您就不这样认为了，每个人的站的角度和知识体系不一样，你觉得容易理解的东西，别人并不一定能理解，如果世界真是像您想的别人马上就能理解就不存在无效沟通的问题了

**Comment by JessYanCoding** [comment]
最后一句话，本不想过多评论了，明显能看出一点情绪在里面

你不了解我的生活怎知道我就只知道代码呢？我现在基本不写业务代码，只是在维护几个开源库的同时管理着公司的团队

你也没和我交流过怎知我情商不高，交流的少呢？我可能交流的不比您少，不管是线上关于开源，博客的交流，还是线下关于公司内部以及外部业务的交流

关于您说的时刻爆裂的玻璃心，这个我觉得可能和您当时的情绪比较贴切，毕竟是你的玻璃心先破裂的，先说出那个气话，我才回复的您的
