### ISSUE TITLE
Api比较多，请问可否支持在ApiService加上class级别的注解，这样不需要给每个方法单独加header了

### ISSUE THREAD

**Issue by baneyue** [JessYanCoding/RetrofitUrlManager#15]
如题，现在项目比较到，给每个方法加domain header还是比较麻烦的

**Comment by JessYanCoding** [comment]
你好，这种方式达到的结果是一样的，但是实现方式和现有方式差别可就大了，现在框架的实现原理是在拦截器里面拦截相关的请求进行相关的处理，因为拦截器里面是可以拿到 Header， 所以不需要做特别的处理就可以框架需要的值

但如果换到 ApiService 上加注解的方式来提供特定的值，在拦截器里面通过普通方式是拿不到  
 ApiService 的注解里的值的，只能通过其他的方式，现在能想到的方式就是通过 AOP，大概有两种方式:

1. 使用 AOP 框架，在编译时，将 ApiService 注解里的值作为 Header 赋值给它下面的所有 Api，这样框架核心代码不用改，AOP 框架帮使用者做了添加 Header 的操作

2. 使用 AOP 框架在编译时生成 ApiService 和 它下面所有 Api 的映射表，框架从在拦截器中提取 Header 改为把每个 URL 和映射表比对，URL 在对应的 ApiService 映射表下，就可以直接从表中取出值 (此种方式略难，因为很多 Api 方法的 Url 会被参数所影响，在编译时是无法确定最终 Url 地址的)

这两种方案，要实现的话，需要一定的时间，并且由于 Gradle 的升级会一定几率影响 Gradle 插件，所以维护上也是有一定的成本，所以在时间非充裕的情况下，我是没时间实现这些功能的 (我还有5个以上的库需要维护...，对不住了兄弟😂)

**如果可以的话, 当然也希望对 AOP 这方面有一定建树的兄弟，能够帮助框架实现**

**Comment by baneyue** [comment]
感谢您的答复。
