### ISSUE TITLE
不同服务器Token问题

### ISSUE THREAD

**Issue by Simon1121** [JessYanCoding/RetrofitUrlManager#16]
大神，我本来加了个拦截器，用于token获取的，但是配上多baseUrl后，就需要区分是哪个domainName返回不同是token。但是domainName被你remove掉了，可有办法解决？（通过监听器监听urlChanged应该会有线程安全问题）

**Comment by JessYanCoding** [comment]
onUrlChanged 执行的监听代码，和你自己在一个新建的拦截器执行一个段代码是一样的，也可以在 RetrofitUrlManager 添加拦截器之前添加一个你自己的拦截器，这样你可以先获取到 header
