### ISSUE TITLE
大神, 真心不知道该怎么用, 使用方式写的不清楚! 望尽快回复,谢谢!

### ISSUE THREAD

**Issue by LinTaoAndroid** [JessYanCoding/RetrofitUrlManager#17]
普通模式
高级模式
超级模式
这三种模式的使用方式写的不够清楚
难道每个uir还需要单独定义一个ApiService 接口吗? 
可以在 App 运行时随意切换某个接口的 BaseUrl? 
本人项目中使用了dagger2
mPresenter.getBanner(1);  (原baseurl)
RetrofitUrlManager.getInstance().putDomain("bo", Constant.BASE_URL_BO);
mPresenter.getAccountBalance(1);(新的baseurl: Constant.BASE_URL_BO)
请问这样使用是否正确?
还有如果是, 多headers 是否有影响? 
   /**
     * 获取首页banner列表
     *
     * @param type
     * @return
     */
    @Headers({
            "Domain-Name: bo",
            "Content-Type: application/json"})
    @GET(Constant.GET_ACCOUNT_BANNERS)
    Observable<HomeBanner> getAccountBalance(@Query("type") int type);

oldBaseUrl:  BASE_URL = "http://192.168.1.85:8088/api/user/v1/
替换
newBaseUrl: BASE_URL_BO = "http://192.168.1.85:8020/"

**Comment by JessYanCoding** [comment]
... 兄弟，这还不清楚？我这篇 [文章](https://www.jianshu.com/p/35a8959c2f86) 写了三千多字来介绍高级模式和超级模式，Demo 和相关 Api 的注释快比代码还多了，如果你还是看不懂，我只能说我表达水平有限，已经尽力，要不你自行看源码理解，要不自己找寻其他方式实现
