### ISSUE TITLE
URLDecoder Error

### ISSUE THREAD

**Issue by junchenChow** [JessYanCoding/RetrofitUrlManager#19]
请求带有%符号的时候 请求就报错了...log 显示这个玩意儿

 java.lang.IllegalArgumentException: URLDecoder: Illegal hex characters in escape (%) pattern : %）3
 at com.jess.arms.http.log.RequestInterceptor.parseParams(RequestInterceptor.java:211)
 at com.jess.arms.http.log.RequestInterceptor.intercept(RequestInterceptor.java:86)

`CharacterHandler.jsonFormat(URLDecoder.decode(requestbuffer.readString(charset), convertCharset(charset)));`指向了这个方法
![inter](https://user-images.githubusercontent.com/13553319/45794676-3f869380-bcca-11e8-9c59-af5d4eb0d91c.png)

**Comment by JessYanCoding** [comment]
兄弟，issues 提出位置了，这是 arms 的问题，并且已经修复，下个版本 release，release 之前要不 builder.printHttpLogLevel(RequestInterceptor.Level.RESPONSE);  关闭请求的打印，要不自己对请求的数据进行 URLEncoder.encode
