### ISSUE TITLE
不知怎么回事就报错了

### ISSUE THREAD

**Issue by huanyuan** [JessYanCoding/RetrofitUrlManager#20]
如下错误：
Missing either @GET URL or @Url parameter.

代码是;
 @Headers({DOMAIN_NAME_HEADER + Api.FILM_NAME})
 @GET("")
  Observable<String> indexPhp();

private NetWorkManager() {
        this.mOkHttpClient = RetrofitUrlManager.getInstance().with(new OkHttpClient.Builder()) //RetrofitUrlManager 初始化
                .readTimeout(5, TimeUnit.SECONDS)
                .connectTimeout(5, TimeUnit.SECONDS)
                .build();

        this.mRetrofit = new Retrofit.Builder()
                .baseUrl(Api.FILM_HOST)
                .addCallAdapterFactory(RxJava2CallAdapterFactory.create())//使用rxjava
                .addConverterFactory(ScalarsConverterFactory.create())//使用Gson
                .client(mOkHttpClient)
                .build();

        this.noLimit91PornService = mRetrofit.create(NoLimit91PornService.class);
        this.film6080Service = mRetrofit.create(Film6080Service.class);
    }

url有的啊，没参数不需要传的

**Comment by JessYanCoding** [comment]
这个是 Retrofit 的报错，和框架无关，它的意思是 @get("") 中必须有参数，这大概是 Retrofit 的规则
