### ISSUE TITLE
多个请求同时发出出现的问题

### ISSUE THREAD

**Issue by LeoCheung0221** [JessYanCoding/RetrofitUrlManager#22]
当一个界面出现多个请求一起请求时，不同的url前缀，进行切换后（我用的是全局BaseUrl），偶尔会出现url错位，我是进行不同的url请求时先全局切换baseUrl的，同时请求可能第一个还没有开始请求但是已经切换全局url了，然后第二个也开始操作，直接切换替换第一个请求的baseUrl, 所以第一个url就不对了，路径就是错误的报404了，第二个却是对的。可以帮忙看看这个问题怎么解决么？谢谢

**Comment by JessYanCoding** [comment]
没听懂你描述的什么，请清晰全面准确的描述问题，以及带上截图或者代码

**Comment by LeoCheung0221** [comment]
比如我的某个功能模块的请求是http://cms.github.com/api/xxx, 另一个请求时http://uic.github.com/api/yyy, 当一起请求时，有时会出现,第二个接口变成http://cms.github.com/api/yyy, 我是进行url拼接然后setGlobalDomain()的，比如cms的api如下，uic也有自己的一个接口类
public interface Api_CMS {
    @Headers({DOMAIN_NAME_HEADER + CMS_DOMAIN_NAME})
    //获取首页数据 - 旧版
    @GET("api/m/mobileHomePage/query")
    Observable<List<HomePageResponse>> getHomePageData();
}
不知道这样描述清晰一点没

**Comment by JessYanCoding** [comment]
CMS_DOMAIN_NAME 设置的 baseUrl 是什么，setGlobalDomain 设置的 baseurl 又是什么，本来的 baseurl 是什么，你只给了一个接口的代码，那么第二个接口的代码又是什么，这些都要描述清楚才晓得你的问题是什么

**Comment by zhanghuibiao** [comment]
你好，楼主，请问这个项目会支持文件上传、下载功能吗，还有取消网络请求操作

**Comment by JessYanCoding** [comment]
@zhanghuibiao 你好，不支持这些功能，因为 RetrofitUrlManager 本身只是依附于 Okhttp 的拦截器而工作的，只具备切换项目中某个 URL 的 baseUrl 的功能，至于 文件上传、下载功能，取消网络请求，这些本身就是 Okhttp 的功能，和 RetrofitUrlManager 这个轻量级框架没什么关系
