### ISSUE TITLE
请教一下RetrofitUrlManager这个类里的方法

### ISSUE THREAD

**Issue by lamster2018** [JessYanCoding/RetrofitUrlManager#23]
你好，很高兴能使用这个好用的开源库，我在阅读代码的时候，在manager类里有几个疑问，
1.manager的registerUrlChangeListener和unregisterUrlChangeListener方法是什么时候调用的，又是谁去调用的？

2.在processRequest方法内，
```
        if (!TextUtils.isEmpty(domainName)) {
            notifyListener(request, domainName, listeners);//内部调用onUrlChangeListener的onUrlChangeBefore方法
            httpUrl = fetchDomain(domainName);
            newBuilder.removeHeader(DOMAIN_NAME);//为什么要删除这个header呢？
```
想问一下，为什么要调用listeners的onUrlChangeBefore方法呢？之后又为什么删除这个header呢？这样做的好处是什么呀？

非常期待你的回答，谢谢

**Comment by lamster2018** [comment]
已经找到源码调用位置了，谢谢老铁

**Comment by JessYanCoding** [comment]
1. 监听器是让外部知道框架内部某些动作的调用时机，并且可以让外部在这个时机调用时做一些操作比如打印日志，registerUrlChangeListener  是外部使用者想使用监听器时调用，unregisterUrlChangeListener 当然是外部使用者不想监听时调用，这个 Android 中的点击事件监听没什么区别，你需要时注册，不需要就不注册

2. header 是框架提供给外部使用者与框架通信的一个方式，header 的生命周期在框架完成对应的操作之后就完结了，如果这里不删除 header，这个 header 就会传给你们家的后台服务器，服务器知道这个 header 没有任何意义，所以直接删除就好

**Comment by lamster2018** [comment]
非常感谢作者的答复！谢谢！
