### ISSUE TITLE
只有一个retrofit实例，但不同模块的接口需要不同的interceptor怎么办？

### ISSUE THREAD

**Issue by macarthor** [JessYanCoding/RetrofitUrlManager#24]
每个模块的接口用的时候addInterceptor，最后就是唯一的OkHttpClient实例拥有所有的interceptor，对每一个request都会带上所有的interceptor来处理？

也许和这个lib无关，但是从“只有一个retrofit实例”这个话题想起的

**Comment by JessYanCoding** [comment]
有几个 retrofit 对象对拦截器的处理并不会有任何影响，拦截器是添加给 OkHttpClient 的，这个你自己看下源码就能清楚，你的描述，也可以这么说，但是不够准确，拦截器用的是责任链模式，OkHttpClient 拥有所有的拦截器，但所有的拦截器并一定都会对同一个 request 进行处理，这个得看拦截器中的具体代码，责任链模式可以百度下
