### ISSUE TITLE
能否做到静态触发和静态配置

### ISSUE THREAD

**Issue by SSourceFile** [JessYanCoding/RetrofitUrlManager#25]
我从网上找了，每一个在拦截器的下面都有你的评论，但是我使用了拦截器的方式导致了okhttp内部异常了。我就是想使用静态的方式多个url访问不同的接口这种情况，我在您代码中貌似没有看到，如果每次都按照你说的在调用接口的地方put，这和@Url没啥区别了，所有想问下静态怎么玩的

**Comment by JessYanCoding** [comment]
可能你理解错了，RetrofitUrlManager 并不需要在每次调用接口的时候 put，如果你 baseUrl 为 A，只要 A 不改变，就不需要 put，如果 A 改变为 B，只需要在需要改变时调用一次 put，后面的所有接口都会使用 B 为 baseUrl，哪怕你有 1000 个接口需要请求，也只需要调用一次 put。

另外，根据你的描述，没明白你说的静态是什么意思。

**Comment by SSourceFile** [comment]
我的意思是我的前端项目中存在A和B的baseUrl，而不是两个地址互相切换的情况，请问这个怎么配置？貌似就的一个个put进去了吧，那和@Url基本没什么差别了

**Comment by JessYanCoding** [comment]
如果你不需要动态切换 BaseUrl，直接使用官方的静态方式就可以了，这个在这篇 [文章](https://www.jianshu.com/p/2919bdb8d09a) 中就介绍了。

至于是否有差别，上面的回复说的很清楚了，这个和 @url 差多了，@url 在每次调用接口时都需要传一遍参数，而 RetrofitUrlManager 只需要在改变时 put 一次，如果你不需要改变，只需要在 App 初始化时 put 一次，后面不管要调用多少次接口都不需要再 put，而带有 @url 的接口，你如果需要调用 1000 次，那不管 baseUrl 是否改变，你都需要传 1000 次 url，这是本质上的区别
