### ISSUE TITLE
retrofitmanager 与glide冲突

### ISSUE THREAD

**Issue by freemub-ios-syb** [JessYanCoding/RetrofitUrlManager#27]
用retrofitmanager动态改变了baseurl，会使glide加载的网络图片url全部替换成baseurl，导致图片404

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/RetrofitUrlManager/blob/master/manager/src/main/java/me/jessyan/retrofiturlmanager/RetrofitUrlManager.java#L360
