### ISSUE TITLE
RetrofitUrlManager和ProgressManager搭配使用

### ISSUE THREAD

**Issue by wangyuan0217** [JessYanCoding/RetrofitUrlManager#28]
如题，要怎么搭配使用

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/RetrofitUrlManager/blob/master/manager/src/main/java/me/jessyan/retrofiturlmanager/RetrofitUrlManager.java#L360   两个库的 with 方法都返回的是 OkHttpClient.Builder，建造者模式怎么用，就不需要我教了把。。。
