### ISSUE TITLE
转换出错

### ISSUE THREAD

**Issue by 424385117** [JessYanCoding/RetrofitUrlManager#31]
我的url是https://xxx.library3.cn/api/,目标url也是这个，转换错误

**Comment by 424385117** [comment]
后面多了个api，变成了https://xxx.library3.cn/api/api

**Comment by SteveYuFun** [comment]
我也遇到这个问题，是不支持带path吗

**Comment by JessYanCoding** [comment]
这个框架是分模式的，有三种模式，普通模式，高级模式，超级模式，高级模式和超级模式是支持 Path 的，目测是你自己配置没正确。

自己认真看一下注释，写的非常详细。[高级模式](https://github.com/JessYanCoding/RetrofitUrlManager/blob/master/manager/src/main/java/me/jessyan/retrofiturlmanager/parser/AdvancedUrlParser.java)、[超级模式](https://github.com/JessYanCoding/RetrofitUrlManager/blob/master/manager/src/main/java/me/jessyan/retrofiturlmanager/parser/SuperUrlParser.java)

**Comment by 424385117** [comment]
> 这个框架是分模式的，有三种模式，普通模式，高级模式，超级模式，高级模式和超级模式是支持 Path 的，目测是你自己配置没正确。
> 
> 自己认真看一下注释，写的非常详细。[高级模式](https://github.com/JessYanCoding/RetrofitUrlManager/blob/master/manager/src/main/java/me/jessyan/retrofiturlmanager/parser/AdvancedUrlParser.java)、[超级模式](https://github.com/JessYanCoding/RetrofitUrlManager/blob/master/manager/src/main/java/me/jessyan/retrofiturlmanager/parser/SuperUrlParser.java)

我换了其他模式，但是报空指针异常

**Comment by JessYanCoding** [comment]
错误日志发出来
