### ISSUE TITLE
多域名解析结果与预期不符

### ISSUE THREAD

**Issue by lrnrzg** [JessYanCoding/RetrofitUrlManager#32]
baseUrl 为 https://xxx.yyy.cn/app/api/ （  初始 retrofit实例设置的 baseUrl ）
domainUrl 为 http://aaa-bbb.yyy.cn/api/ （putDomain 设置的 domainUrl ）
在 @Headers 中引用 domainUrl， 且设置 @GET("teacher/classOption")
异常结果却为   http://aaa-bbb.cn/api/app/api/teacher/classOption ， 
预期应该为 http://aaa-bbb.yyy.cn/api/teacher/classOption

**Comment by lrnrzg** [comment]
现象上来看， 最终结果的 domainUrl 不应该拼接 baseUrl 的路径呀

**Comment by ZhuSniffsTheRose** [comment]
后面思考和看代码发现，此库不支持路径的替换， 用户得严格将  baseUrl  or domainUrl 设置为域名， 而不能将每个请求公有路径放于其中，即需要将 app/api/ 声明至 get or post 这样的注解中.

**Comment by ZhuSniffsTheRose** [comment]
> 现象上来看， 最终结果的 domainUrl 不应该拼接 baseUrl 的路径呀
后面思考和看代码发现，此库不支持路径的替换， 用户得严格将 baseUrl or domainUrl 设置为域名， 而不能将每个请求公有路径放于其中，即需要将 app/api/ 声明至 get or post 这样的注解中.

**Comment by lrnrzg** [comment]
> 现象上来看， 最终结果的 domainUrl 不应该拼接 baseUrl 的路径呀

后面思考和看代码发现，此库不支持路径的替换， 用户得严格将 baseUrl or domainUrl 设置为域名， 而不能将每个请求公有路径放于其中，即需要将 app/api/ 声明至 get or post 这样的注解中.

**Comment by JessYanCoding** [comment]
> > 现象上来看， 最终结果的 domainUrl 不应该拼接 baseUrl 的路径呀
> 
> 后面思考和看代码发现，此库不支持路径的替换， 用户得严格将 baseUrl or domainUrl 设置为域名， 而不能将每个请求公有路径放于其中，即需要将 app/api/ 声明至 get or post 这样的注解中.

兄弟，你竟然说你认真看了代码，那你这个结论怎么得出来的。。。，就算不看代码，注释也写的很清楚啊。

第一个版本确实只支持 domain 的替换，但是后面更新的版本，就已经添加了 **高级模式** 和 **超级模式**，你就算 domain 后面有 1000 个 pathSegments，都是支持的，建议认真看下 [注释](https://github.com/JessYanCoding/RetrofitUrlManager/blob/master/manager/src/main/java/me/jessyan/retrofiturlmanager/RetrofitUrlManager.java#L46)。

你这种情况明显只使用了普通模式，在 [普通模式的注释里](https://github.com/JessYanCoding/RetrofitUrlManager/blob/master/manager/src/main/java/me/jessyan/retrofiturlmanager/parser/DomainUrlParser.java#L30) 就写的很清楚了，普通模式支持域名的替换。

你这个情况使用 [高级模式](https://github.com/JessYanCoding/RetrofitUrlManager/blob/master/manager/src/main/java/me/jessyan/retrofiturlmanager/parser/AdvancedUrlParser.java#L30) 就可以解决了。

就怕你们不清楚，注释我还认真写了上千字，结果都不看的，吐血。。。

**Comment by lrnrzg** [comment]
大哥， 我的锅， 谢谢指点。
