### ISSUE TITLE
大佬关于BaseUrl的问题

### ISSUE THREAD

**Issue by WangStormstout** [JessYanCoding/RetrofitUrlManager#33]
我们的URL以前是 http://test.xxx.cn/ 然后后面拼接业务具体的
我是用的你的模块化 新的项目 变成了 http://test.xxx.cn/test/ 然后后面拼接业务
然后就导致了链接变成了  http://test.xxx.cn/test/ test/ 加业务
我在文档里面看到了    public static final String IDENTIFICATION_IGNORE = "#url_ignore";
我就添加了 http://test.xxx.cn/test/#url_ignore 依然没用.
我先试试高级模式

**Comment by JessYanCoding** [comment]
抱歉，没听懂你想表达什么问题

**Comment by WangStormstout** [comment]
我已经解决了 用了 高级模式就好了 非常感谢开源
