### ISSUE TITLE
使用@Url注解的接口，传入的url会被globalDomain覆盖

### ISSUE THREAD

**Issue by huluwa-dev** [JessYanCoding/RetrofitUrlManager#7]
通过RetrofitUrlManager.getInstance().setGlobalDomain方法设置了baseUrl。

现在我有个接口想要用一个单独的host来访问，接口定义如下：
@GET
 fun ping(@Url url: String): Call<PingVO>

请求的时候，此方法中传入的我想要的url会被之前设置的baseUrl覆盖。
望修复。

**Comment by JessYanCoding** [comment]
修复不了, 要不使用 setRun(false), 停止框架, 要不使用框架自定义 Header  的方式替换 Domain

**Comment by huluwa-dev** [comment]
666

**Comment by JessYanCoding** [comment]
你看了源码也就明白为啥修复不了, 因为框架并不知道你哪个接口使用了 @Url 的方式哪些是普通方式, 他只会默认全部处理, 你必须使用 Header 告诉它应该处理哪个

**Comment by huluwa-dev** [comment]
好的，多谢。

**Comment by JessYanCoding** [comment]
@EricInCD 升级到最新版, 将 @url 注解的地址传入 RetrofitUrlManager.getInstance().setUrlNotChange(String), 会返回经过处理的 Url 地址,  将此地址传入你上面定义的请求方法，即可避免被替换
