### ISSUE TITLE
使用Headers标识主机名，在Intercepter中提取Header替换host可能会有问题

### ISSUE THREAD

**Issue by cnneillee** [JessYanCoding/RetrofitUrlManager#8]
这种方式，我之前在项目中实践过。
使用过程中，遇到这样的问题：
在访问Https时，在某些手机上，会出现异常：
`java.security.cert.CertPathValidatorException: Trust anchor for certification path not found`。

请问你有没有遇到过这样的问题，对于此种问题，有没有什么更好的办法？

**Comment by JessYanCoding** [comment]
兄弟你知道请求 **Https** 的网站时需要额外配置一些参数吗
